#!/usr/bin/env python


import os
import shutil
import torch
from diffusers import DiffusionPipeline

MODEL_CACHE = "model-cache"
TMP_CACHE = "tmp-cache"

if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)

pipe = DiffusionPipeline.from_pretrained(
    "cerspense/zeroscope_v2_XL",
    torch_dtype=torch.float16,
    cache_dir=TMP_CACHE,
)

pipe.save_pretrained(MODEL_CACHE)

shutil.rmtree(TMP_CACHE)